# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='camera_sampler',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rservice.proto\x12\x0e\x63\x61mera_sampler\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x05Reply\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x13\n\x0bimage_shape\x18\x02 \x03(\x05\x32O\n\rCameraSampler\x12>\n\x0bSampleImage\x12\x16.google.protobuf.Empty\x1a\x15.camera_sampler.Reply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='camera_sampler.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='camera_sampler.Reply.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_shape', full_name='camera_sampler.Reply.image_shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:camera_sampler.Reply)
  })
_sym_db.RegisterMessage(Reply)



_CAMERASAMPLER = _descriptor.ServiceDescriptor(
  name='CameraSampler',
  full_name='camera_sampler.CameraSampler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='SampleImage',
    full_name='camera_sampler.CameraSampler.SampleImage',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERASAMPLER)

DESCRIPTOR.services_by_name['CameraSampler'] = _CAMERASAMPLER

# @@protoc_insertion_point(module_scope)
